### ISSUE TITLE
Un-cancelling InventoryClickEvent

### ISSUE THREAD

**Issue by elijuh** [iInvisibilities/Report#1]
I noticed that in your inventory listener you're setting the cancelled value according to if the player is in the reports menu or not, which is terrible practice and can mess up the inventory handling of any other listener trying to cancel it.

located at (https://github.com/iInvisibilities/Report/blob/main/src/main/java/me/invis/report/listener/SimplePrevent.java#L11)

I would recommend either checking if the event isn't already cancelled (That way you avoid un-cancelling an event that has been cancelled), or putting your condition in an 'if' statement so that you only effect the event when it's your GUI.

just wanted to help :)

**Comment by iInvisibilities** [comment]
This is actually logical after rethinking about it, & since it doesn't really do any harm if i put an if statement, i'll do it without checking if it's actually true or not, Thanks!
